services:
  db:
    image: postgres:latest
    container_name: doni_db
    environment:
      POSTGRES_USER: doni
      POSTGRES_PASSWORD: donidb1234thisisanexample
      POSTGRES_DB: doni_db
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "obaas", "-d", "obaas"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Adminer for database management (optional)
  adminer:
    image: adminer:latest
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db:5432
      - ADMINER_DEFAULT_DB=doni_db
      - ADMINER_DEFAULT_USER=doni
    restart: unless-stopped
