name: Deploy Vite site to Pages

on:
  # Déclencher sur push et pull request
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types: [opened, synchronize, reopened]
  
  # Permet de lancer le workflow manuellement
  workflow_dispatch:

# Définir les permissions nécessaires pour GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Empêcher l'exécution simultanée de plusieurs déploiements
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      # Ne déployer que si c'est un push sur main ou une action manuelle
      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        id: deployment
        uses: actions/deploy-pages@v4